name: Linux

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v2

      - uses: zzvio/setup-graalvm@5.3
        with:
          graalvm: '21.3.0-dev-20210831_2241'
          java: java11

      - name: Gluon Build
        run: cd gojni; mvn gluonfx:build

      # - name: Make staging directory
      #   run: mkdir staging

      # - name: Copy GoIPFS to staging
      #   run: cp -r gojni/target/gluonfx/x86_64-linux/GoIPFS staging

      # - name: Upload
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Package
      #     path: staging

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - run: |
          mkdir -p $dest ~/.java/packages/lib/
          cd cmd/ipfs; \
          CGO_CFLAGS="-I${PWD}" go build -o libgoipfs.so -buildmode=c-shared; \
          cp libgoipfs.so ~/.java/packages/lib/

      - name: Test compiled java
        run: gojni/target/gluonfx/x86_64-linux/GoIPFS & sleep 5; kill $!

      - name: Upload 
        uses: zzvio/action-megacmd@master
        with:
          args: put -c ~/.java/packages/lib/libgoipfs.so /go-plugins/ipfs/Linux-x86_64/libgoipfs.so
        env:
          USERNAME: ${{ secrets.MEGA_USERNAME }}
          PASSWORD: ${{ secrets.MEGA_PASSWORD }}
